### ISSUE TITLE
KeyError: 'fields' when using bigmler analyze

### ISSUE THREAD

**Issue by ajmazurie** [bigmlcom/bigmler#173] opened 2016-06-01 22:46 UTC
Hi,
I have been using `bigmler analyze` with the following options:

``` bash
bigmler analyze --features \
    --dataset "${DATASET_ID}" \
    --penalty 0.002 --staleness 3 --k-folds 2 \
    --predictions-csv \
    --optimize-category='True' \
    --optimize precision
```

And I'm getting the following error:

``` console
Creating the best features set..........
Traceback (most recent call last):
  File ".../.env/pyenv-2.7.10-default/bin/bigmler", line 11, in <module>
    sys.exit(main())
  File ".../.env/pyenv-2.7.10-default/lib/python2.7/site-packages/bigmler/bigmler.py", line 97, in main
    analyze_dispatcher(args=new_args)
  File ".../.env/pyenv-2.7.10-default/lib/python2.7/site-packages/bigmler/analyze/dispatcher.py", line 117, in analyze_dispatcher
    resume=resume)
  File ".../.env/pyenv-2.7.10-default/lib/python2.7/site-packages/bigmler/analyze/k_fold_cv.py", line 239, in create_features_analysis
    objective_name=objective_name, resume=resume)
  File ".../.env/pyenv-2.7.10-default/lib/python2.7/site-packages/bigmler/analyze/k_fold_cv.py", line 586, in best_first_search
    fields = Fields(dataset)
  File ".../.env/pyenv-2.7.10-default/lib/python2.7/site-packages/bigml/fields.py", line 175, in __init__
    resource_info = get_fields_structure(resource_or_fields, True)
  File ".../.env/pyenv-2.7.10-default/lib/python2.7/site-packages/bigml/fields.py", line 116, in get_fields_structure
    fields = resource['fields']
KeyError: 'fields'
```

Any idea what is causing this? If you want to reproduce this, the dataset ID is `dataset/574f4a0c7e0a8d09ab0093ae`.

Best,
Aurélien

**Comment by mmerce** [comment] 2016-06-01 23:39
Hi Aurélien,

I've not been able to reproduce the error you mention. As you know, resources in BigML are private, so unless they are explicitly shared using the corresponding configuration option, cannot be accessed, and you better don't do that here, considering this is a public repo. However, I don't think your problem is caused by your dataset being unusual.

The error appears when BigMLer tries to read the fields structure in the datasets created by dividing the one you mention. This structure should be available if the partial dataset have been correctly generated, so we'd need to investigate further what has caused it not to be there.  Could you please send to support@bigml.com the contents of the output directory that has been generated when running the bigmler command? a .gz or .zip would do. Thanks.

**Comment by mmerce** [comment] 2017-07-28 09:22
Closing because we were unable to reproduce this error. Please reopen if you still see the issue or write to support with an excerpt of you dataset. Thanks!

**Closed by mmerce** 2017-07-28 09:22 UTC
