### ISSUE TITLE
when running a batch prediction, predictions.csv can be incomplete

### ISSUE THREAD

**Issue by devTristan** [bigmlcom/bigmler#147] opened 2015-10-13 15:05 UTC
Ran a batch prediction on 50k rows. This usually works. Got an incomplete predictions.csv file back, despite no complaints from bigmler. It exited with code 0 and appeared to work fine. The file was cut off after about 10k records, halfway through a line.

My guess is that it should catch any errors and retry.

**Comment by mmerce** [comment] 2015-10-13 15:21
I'm trying to reproduce that. I'll let you know.

**Comment by devTristan** [comment] 2015-10-13 20:23
I've run a few hundred batch predictions and only gotten it the once.

**Comment by mmerce** [comment] 2015-10-13 23:12
Probably this will be due to a transient connection problem, and I've not been able to reproduce it. Moreover, some people complain about similar things happening with the `requests` library with no error indicator appearing. I'll try to produce a sounder version checking the `content-length` header.

**Comment by devTristan** [comment] 2015-10-13 23:21
Thanks :)

**Comment by mmerce** [comment] 2015-10-16 16:05
Please, check the version 3.3.1 of bigmler that includes a new bindings version checking `content-length` header.

**Comment by devTristan** [comment] 2015-10-16 17:41
Will do, and I'll come back if I experience the issue again.

**Comment by mmerce** [comment] 2015-11-01 18:46
Closing this issue. If you experience the issue again, please reopen.

**Closed by mmerce** 2015-11-01 18:46 UTC
